### PR TITLE
Create Median Of two sorted Array

### PR DESCRIPTION
**Pull request by Tanishka534**
I have created java file , solution of problem median of two sorted array, kindly please merge this.

Here are Related output screenshots->

Screenshot 2024-10-01 at 2 40 06 PM

### CODE REVIEW

**Review by Saloni6111 — COMMENTED** [review]
you already added FizzBuzz code in java then why again in cpp? remove it will merge it after that.

**Comment by Tanishka534** [comment]
okay mam

**Comment by Tanishka534** [comment]
Mam , i have removed that, now you can merge, 
kindly please merge it

**Comment by Saloni6111** [comment]
> Mam , i have removed that, now you can merge, kindly please merge it

done!

**Pull request merged**
